name: Blocklist compile

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm i -g @adguard/hostlist-compiler
    - run: hostlist-compiler -c blocklist/basic.json -o output.txt
    - name: Upload compiled artifact
      uses: actions/upload-artifact@v2
      with:
        name: basic
        path: output.txt
    
