name: Blocklist compile

on:
  schedule:
    - cron: "0 0 * * *"   # every day at 12:00 am (midnight)


permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm i -g @adguard/hostlist-compiler
    - run: hostlist-compiler -c blocklist/basic.json -o basic.txt
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update blocklist
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: basic-blocklist.txt
