name: Blocklist compile

on:
  pull_request:
  schedule:
    - cron: "0 5 * * *"   # every day at 05:00 am


permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: npm i -g @adguard/hostlist-compiler
    - run: hostlist-compiler -c basic.json -o basic.txt
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Nightly update blocklist
        commit_user_name: Dungeon master
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: basic-blocklist.txt
